<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="jakarta.tags.core" %>
<!DOCTYPE html><html lang="vi"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Đăng nhập · HCMUTE Shop</title><script src="${pageContext.request.contextPath}/assets/js/theme.js"></script><link rel="preconnect" href="https://fonts.googleapis.com"><link href="https://fonts.googleapis.com/css2?family=DM+Mono:wght@400;500&family=Plus+Jakarta+Sans:wght@400;500;600;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="${pageContext.request.contextPath}/assets/css/dashboard.css"></head>
<body class="auth-body"><button class="icon-button theme-toggle auth-theme-toggle" data-theme-toggle type="button" aria-label="Chuyển chế độ giao diện"><span class="theme-symbol theme-symbol-sun" aria-hidden="true">☀</span><span class="theme-symbol theme-symbol-moon" aria-hidden="true">☾</span></button><div class="auth-shell">
<aside class="auth-aside"><a class="auth-brand" href="${pageContext.request.contextPath}/home"><img class="brand-logo" src="${pageContext.request.contextPath}/assets/images/logo.jpg" alt="Logo HCM-UTE">HCMUTE Shop</a><div class="auth-highlight"><p class="hero-eyebrow">Quản trị bán hàng</p><h2>Mọi chỉ số quan trọng, trong một nơi.</h2><p>Theo dõi sản phẩm, danh mục và vận hành cửa hàng bằng một giao diện rõ ràng.</p><div class="auth-stats"><div class="auth-stat"><span>Quản lý sản phẩm</span><strong>CRUD</strong></div><div class="auth-stat"><span>Bảo mật tài khoản</span><strong>OTP</strong></div><div class="auth-stat"><span>Phiên đăng nhập</span><strong>SESSION</strong></div></div></div><span class="auth-copy">© 2026 HCMUTE Shop</span></aside>
<main class="auth-main"><div class="auth-card"><a class="auth-brand mobile-only" style="margin-bottom:30px" href="${pageContext.request.contextPath}/home"><img class="brand-logo" src="${pageContext.request.contextPath}/assets/images/logo.jpg" alt="Logo HCM-UTE">HCMUTE Shop</a><h1>Đăng nhập</h1><p class="auth-lead">Sử dụng tài khoản đã kích hoạt để tiếp tục.</p>
<c:if test="${not empty sessionScope.authMessage}"><div class="alert alert-success" style="margin-bottom:14px"><c:out value="${sessionScope.authMessage}"/></div><c:remove var="authMessage" scope="session"/></c:if>
<c:if test="${not empty error}"><div class="alert alert-error" style="margin-bottom:14px"><c:out value="${error}"/></div></c:if>
<form class="auth-form" action="${pageContext.request.contextPath}/login" method="post">
<div class="field"><label for="username">Tên đăng nhập hoặc email</label><input class="form-control" id="username" name="username" value="<c:out value='${not empty param.username ? param.username : rememberedUsername}'/>" required autofocus autocomplete="username" placeholder="admin"></div>
<div class="field"><div class="auth-between"><label for="password">Mật khẩu</label><a class="auth-link" href="${pageContext.request.contextPath}/forgot-password">Quên mật khẩu?</a></div><input class="form-control" id="password" name="password" type="password" minlength="6" required autocomplete="current-password" placeholder="••••••••"></div>
<label class="check-line"><input type="checkbox" name="remember" ${not empty rememberedUsername ? 'checked' : ''}> Ghi nhớ tên đăng nhập bằng Cookie</label>
<button class="btn btn-primary auth-submit" type="submit">Đăng nhập →</button></form><p class="auth-bottom">Chưa có tài khoản? <a class="auth-link" href="${pageContext.request.contextPath}/register">Đăng ký ngay</a></p></div></main>
</div></body></html>
