<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%><%@ taglib prefix="c" uri="jakarta.tags.core" %>
<!DOCTYPE html><html lang="vi"><head><meta charset="UTF-8"><title>${editing ? 'Chỉnh sửa sản phẩm' : 'Thêm sản phẩm'}</title></head><body>
<div class="page-stack"><div class="page-heading"><div><p class="page-kicker">Quản lý sản phẩm</p><h1 class="page-title">${editing ? 'Chỉnh sửa sản phẩm' : 'Tạo sản phẩm mới'}</h1><p class="page-subtitle">Thông tin được lưu bằng JPA và ảnh được xử lý bằng Multipart.</p></div></div><c:if test="${not empty error}"><div class="alert alert-error"><c:out value="${error}"/></div></c:if>
<form id="productForm" action="${pageContext.request.contextPath}${editing ? '/admin/product/update' : '/admin/product/insert'}" method="post" enctype="multipart/form-data" novalidate><c:if test="${editing}"><input type="hidden" name="productId" value="${product.productId}"></c:if><div class="form-layout"><section class="panel"><div class="panel-header"><div><h2 class="panel-title">Thông tin sản phẩm</h2><p class="panel-subtitle">Các trường có dấu * là bắt buộc.</p></div><span class="status ${editing ? 'status-active' : 'status-warning'}">${editing ? 'Đang chỉnh sửa' : 'Bản ghi mới'}</span></div><div class="form-section"><div class="form-grid">
<div class="field full"><label for="productName">Tên sản phẩm *</label><input class="form-control" id="productName" name="productName" value="<c:out value='${product.productName}'/>" minlength="3" maxlength="255" required autofocus></div>
<div class="field"><label for="categoryId">Danh mục *</label><select class="form-control" id="categoryId" name="categoryId" required><option value="">Chọn danh mục</option><c:forEach items="${categories}" var="cate"><option value="${cate.categoryId}" ${product.category.categoryId == cate.categoryId ? 'selected' : ''}><c:out value="${cate.categoryname}"/></option></c:forEach></select></div>
<div class="field"><label for="price">Giá bán (VNĐ) *</label><input class="form-control mono" id="price" name="price" type="number" min="0" step="1000" value="${product.price}" required></div>
<div class="field"><label for="quantity">Số lượng tồn *</label><input class="form-control mono" id="quantity" name="quantity" type="number" min="0" step="1" value="${product.quantity}" required></div>
<div class="field"><label>Trạng thái *</label><div class="choice-grid"><div><input class="choice-input" type="radio" id="active" name="status" value="1" ${!editing || product.status == 1 ? 'checked' : ''}><label class="choice-card" for="active"><span class="choice-radio"></span><span class="choice-title">Đang bán</span></label></div><div><input class="choice-input" type="radio" id="paused" name="status" value="0" ${editing && product.status == 0 ? 'checked' : ''}><label class="choice-card" for="paused"><span class="choice-radio"></span><span class="choice-title">Tạm ẩn</span></label></div></div></div>
<div class="field full"><label for="description">Mô tả <span class="field-hint">Tối đa 2000 ký tự</span></label><textarea class="form-control" id="description" name="description" maxlength="2000" rows="5"><c:out value="${product.description}"/></textarea></div>
<div class="field full"><label for="imageFile">${editing ? 'Thay ảnh sản phẩm' : 'Ảnh sản phẩm'} <span class="field-hint">JPG, PNG, GIF, WEBP · tối đa 10MB</span></label><input class="form-control" id="imageFile" name="imageFile" type="file" accept="image/jpeg,image/png,image/gif,image/webp"></div>
<div class="field full"><label for="images">Hoặc URL ảnh online</label><input class="form-control" id="images" name="images" type="url" value="${not empty product.images && product.images.startsWith('http') ? product.images : ''}" placeholder="https://example.com/product.jpg"></div>
</div></div><div class="form-footer"><a class="btn" href="${pageContext.request.contextPath}/admin/products">← Quay lại</a><button class="btn btn-primary" type="submit">${editing ? 'Lưu thay đổi' : 'Tạo sản phẩm'} →</button></div></section>
<aside class="panel preview-card"><h2 class="panel-title">Xem trước ảnh</h2><p class="panel-subtitle" style="margin-bottom:14px">Ảnh sản phẩm hiển thị theo tỷ lệ vuông.</p><div class="preview-frame" style="aspect-ratio:1"><div class="preview-empty" id="previewEmpty" ${not empty product.images ? 'hidden' : ''}>Chọn tệp hoặc dán URL<br>để xem trước</div><c:choose><c:when test="${not empty product.images && product.images.startsWith('http')}"><img id="imagePreview" src="${product.images}" alt="Ảnh xem trước"></c:when><c:when test="${not empty product.images}"><img id="imagePreview" src="${pageContext.request.contextPath}/image?fname=${product.images}" alt="Ảnh xem trước"></c:when><c:otherwise><img id="imagePreview" alt="Ảnh xem trước" hidden></c:otherwise></c:choose></div><p class="preview-note">Khuyến nghị ảnh vuông tối thiểu 800×800px.</p></aside></div></form></div>
<script>(function(){const form=document.getElementById('productForm'),file=document.getElementById('imageFile'),url=document.getElementById('images'),img=document.getElementById('imagePreview'),empty=document.getElementById('previewEmpty');function show(src){img.src=src;img.hidden=false;empty.hidden=true}file.addEventListener('change',()=>{if(file.files&&file.files[0])show(URL.createObjectURL(file.files[0]))});url.addEventListener('input',()=>{if(/^https?:\/\//i.test(url.value.trim()))show(url.value.trim())});img.addEventListener('error',()=>{img.hidden=true;empty.hidden=false});form.addEventListener('submit',e=>{if(!form.checkValidity()){e.preventDefault();form.querySelector(':invalid').focus()}})})();</script>
</body></html>
