<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="jakarta.tags.core" %><%@ taglib prefix="fmt" uri="jakarta.tags.fmt" %>
<!DOCTYPE html><html lang="vi"><head><meta charset="UTF-8"><title>Sản phẩm</title></head><body>
<div class="page-stack">
<div class="page-heading"><div><p class="page-kicker">Quản lý kho hàng</p><h1 class="page-title">Sản phẩm</h1><p class="page-subtitle">CRUD sản phẩm bằng JPA, tìm kiếm và phân trang phía server.</p></div><a class="btn btn-primary" href="${pageContext.request.contextPath}/admin/product/add">+ Thêm sản phẩm</a></div>
<c:if test="${not empty sessionScope.adminMessage}"><div class="alert alert-success"><c:out value="${sessionScope.adminMessage}"/></div><c:remove var="adminMessage" scope="session"/></c:if><c:if test="${not empty sessionScope.adminError}"><div class="alert alert-error"><c:out value="${sessionScope.adminError}"/></div><c:remove var="adminError" scope="session"/></c:if>
<section class="metric-grid equal"><article class="metric-cell"><p class="metric-label">Tổng sản phẩm</p><p class="metric-value">${total}</p></article><article class="metric-cell"><p class="metric-label">Kích thước trang</p><p class="metric-value">10</p></article><article class="metric-cell"><p class="metric-label">Trang hiện tại</p><p class="metric-value">${page}</p></article><article class="metric-cell"><p class="metric-label">Tổng số trang</p><p class="metric-value">${totalPages}</p></article></section>
<section class="panel"><form class="toolbar" action="${pageContext.request.contextPath}/admin/products" method="get"><div class="toolbar-actions"><div class="search-field"><svg width="12" height="12" viewBox="0 0 16 16" fill="none"><circle cx="7" cy="7" r="5" stroke="currentColor" stroke-width="1.5"/><path d="m11 11 3 3" stroke="currentColor" stroke-width="1.5"/></svg><input id="tableSearch" name="q" value="<c:out value='${q}'/>" placeholder="Tìm tên sản phẩm..."></div><select class="form-control" name="category" style="width:190px;min-height:32px"><option value="">Tất cả danh mục</option><c:forEach items="${categories}" var="cate"><option value="${cate.categoryId}" ${selectedCategory == cate.categoryId ? 'selected' : ''}><c:out value="${cate.categoryname}"/></option></c:forEach></select><button class="btn" type="submit">Lọc dữ liệu</button><a class="btn btn-ghost" href="${pageContext.request.contextPath}/admin/products">Đặt lại</a></div></form>
<div class="table-scroll"><table class="data-table"><thead><tr><th>ID</th><th>Sản phẩm</th><th>Danh mục</th><th>Giá</th><th>Tồn kho</th><th>Trạng thái</th><th style="text-align:right">Thao tác</th></tr></thead><tbody>
<c:choose><c:when test="${empty products}"><tr><td colspan="7" class="empty-state">Không có sản phẩm phù hợp.<br><a style="color:var(--accent)" href="${pageContext.request.contextPath}/admin/product/add">Tạo sản phẩm đầu tiên →</a></td></tr></c:when><c:otherwise><c:forEach items="${products}" var="product"><tr><td class="table-id">P-${product.productId}</td><td><div class="name-cell"><c:choose><c:when test="${not empty product.images && product.images.startsWith('http')}"><img class="thumb" src="${product.images}" alt="" loading="lazy"></c:when><c:when test="${not empty product.images}"><img class="thumb" src="${pageContext.request.contextPath}/image?fname=${product.images}" alt="" loading="lazy" onerror="this.style.display='none'"></c:when><c:otherwise><span class="thumb thumb-placeholder">P</span></c:otherwise></c:choose><span><span class="table-primary"><c:out value="${product.productName}"/></span><span class="name-detail">${product.quantity > 0 ? 'Còn hàng' : 'Hết hàng'}</span></span></div></td><td><c:out value="${product.category.categoryname}"/></td><td class="mono table-primary"><fmt:formatNumber value="${product.price}" type="number" maxFractionDigits="0"/>₫</td><td class="mono">${product.quantity}</td><td><span class="status ${product.status == 1 ? (product.quantity > 0 ? 'status-active' : 'status-warning') : 'status-paused'}">${product.status == 1 ? (product.quantity > 0 ? 'Đang bán' : 'Hết hàng') : 'Tạm ẩn'}</span></td><td><div class="cell-actions"><a class="btn btn-sm" href="${pageContext.request.contextPath}/admin/product/edit?id=${product.productId}">Sửa</a><a class="btn btn-sm btn-danger" href="${pageContext.request.contextPath}/admin/product/delete?id=${product.productId}" onclick="return confirm('Bạn có chắc muốn xóa sản phẩm này?')">Xóa</a></div></td></tr></c:forEach></c:otherwise></c:choose>
</tbody></table></div></section>
<c:if test="${totalPages > 1}"><nav class="pagination" aria-label="Phân trang"><c:forEach begin="1" end="${totalPages}" var="p"><c:url var="pageUrl" value="/admin/products"><c:param name="page" value="${p}"/><c:if test="${not empty q}"><c:param name="q" value="${q}"/></c:if><c:if test="${not empty selectedCategory}"><c:param name="category" value="${selectedCategory}"/></c:if></c:url><a class="page-link ${p == page ? 'active' : ''}" href="${pageUrl}">${p}</a></c:forEach></nav></c:if>
</div></body></html>
